<?php

return [
    'public_ctas' => [
        'audit'              => 'Lancer mon audit gratuit',
        'audit_free'         => 'Lancer mon audit gratuit',
        'scan'               => 'Débloquer le Diagnostic',
        'essential'          => 'Commencer avec Essentiel',
        'continuous_control' => 'Activer la Maîtrise',
        'scale'              => 'Parler à l\'équipe',
        'create_account'     => 'Créer mon compte',
    ],

    'providers' => [
        'openai' => [
            'id' => 'openai',
            'label' => 'OpenAI',
        ],
        'anthropic' => [
            'id' => 'anthropic',
            'label' => 'Anthropic',
        ],
        'google' => [
            'id' => 'google',
            'label' => 'Google (Gemini)',
        ],
        'mistral' => [
            'id' => 'mistral',
            'label' => 'Mistral',
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Audit Model Catalog
    |--------------------------------------------------------------------------
    | Broader catalog used for the public audit form.
    | controlled_v1: true = runtime proxy enforcement is active in Margexa V1.
    | Distinct from `models` which are the 4 runtime-controlled models only.
    */
    'audit_models' => [
        // OpenAI — controlled V1
        'gpt-4o-mini' => [
            'id'            => 'gpt-4o-mini',
            'label'         => 'GPT-4o Mini',
            'provider'      => 'openai',
            'controlled_v1' => true,
        ],
        'gpt-4o' => [
            'id'            => 'gpt-4o',
            'label'         => 'GPT-4o',
            'provider'      => 'openai',
            'controlled_v1' => true,
        ],
        // OpenAI — audited, not yet controlled
        'gpt-4-turbo' => [
            'id'            => 'gpt-4-turbo',
            'label'         => 'GPT-4 Turbo',
            'provider'      => 'openai',
            'controlled_v1' => false,
        ],
        'gpt-3.5-turbo' => [
            'id'            => 'gpt-3.5-turbo',
            'label'         => 'GPT-3.5 Turbo',
            'provider'      => 'openai',
            'controlled_v1' => false,
        ],
        'o1-mini' => [
            'id'            => 'o1-mini',
            'label'         => 'O1 Mini',
            'provider'      => 'openai',
            'controlled_v1' => false,
        ],
        'o1' => [
            'id'            => 'o1',
            'label'         => 'O1',
            'provider'      => 'openai',
            'controlled_v1' => false,
        ],
        // Anthropic — controlled V1
        'claude-3-5-haiku' => [
            'id'            => 'claude-3-5-haiku',
            'label'         => 'Claude 3.5 Haiku',
            'provider'      => 'anthropic',
            'controlled_v1' => true,
        ],
        'claude-3-5-sonnet' => [
            'id'            => 'claude-3-5-sonnet',
            'label'         => 'Claude 3.5 Sonnet',
            'provider'      => 'anthropic',
            'controlled_v1' => true,
        ],
        // Anthropic — audited, not yet controlled
        'claude-3-opus' => [
            'id'            => 'claude-3-opus',
            'label'         => 'Claude 3 Opus',
            'provider'      => 'anthropic',
            'controlled_v1' => false,
        ],
        'claude-3-haiku' => [
            'id'            => 'claude-3-haiku',
            'label'         => 'Claude 3 Haiku',
            'provider'      => 'anthropic',
            'controlled_v1' => false,
        ],
        // Google Gemini — audited, not yet controlled
        'gemini-1.5-pro' => [
            'id'            => 'gemini-1.5-pro',
            'label'         => 'Gemini 1.5 Pro',
            'provider'      => 'google',
            'controlled_v1' => false,
        ],
        'gemini-1.5-flash' => [
            'id'            => 'gemini-1.5-flash',
            'label'         => 'Gemini 1.5 Flash',
            'provider'      => 'google',
            'controlled_v1' => false,
        ],
        // Mistral — audited, not yet controlled
        'mistral-large' => [
            'id'            => 'mistral-large',
            'label'         => 'Mistral Large',
            'provider'      => 'mistral',
            'controlled_v1' => false,
        ],
        'mistral-7b-instruct' => [
            'id'            => 'mistral-7b-instruct',
            'label'         => 'Mistral 7B Instruct',
            'provider'      => 'mistral',
            'controlled_v1' => false,
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Runtime Model Catalog
    |--------------------------------------------------------------------------
    | Margexa works for any AI workflow — not limited to support.
    | controlled_v1 = proxy enforcement is active for this model.
    | Gemini: proxy returns 501 "Google provider coming in V2".
    */
    'models' => [
        // ── OpenAI ────────────────────────────────────────────────────────
        'gpt-4o-mini' => [
            'id' => 'gpt-4o-mini',
            'label' => 'GPT-4o Mini',
            'provider' => 'openai',
            'tier' => 'economy',
            'fallback_allowed' => true,
            'premium' => false,
            'costs' => ['input' => 0.00015, 'output' => 0.0006],
        ],
        'gpt-4o' => [
            'id' => 'gpt-4o',
            'label' => 'GPT-4o',
            'provider' => 'openai',
            'tier' => 'premium',
            'fallback_allowed' => false,
            'premium' => true,
            'costs' => ['input' => 0.005, 'output' => 0.015],
        ],
        // ── Anthropic ─────────────────────────────────────────────────────
        'claude-3-5-haiku' => [
            'id' => 'claude-3-5-haiku',
            'label' => 'Claude 3.5 Haiku',
            'provider' => 'anthropic',
            'tier' => 'economy',
            'fallback_allowed' => true,
            'premium' => false,
            'costs' => ['input' => 0.00025, 'output' => 0.00125],
        ],
        'claude-3-5-sonnet' => [
            'id' => 'claude-3-5-sonnet',
            'label' => 'Claude 3.5 Sonnet',
            'provider' => 'anthropic',
            'tier' => 'premium',
            'fallback_allowed' => false,
            'premium' => true,
            'costs' => ['input' => 0.003, 'output' => 0.015],
        ],
        'claude-sonnet-4' => [
            'id' => 'claude-sonnet-4',
            'label' => 'Claude Sonnet 4',
            'provider' => 'anthropic',
            'tier' => 'premium',
            'fallback_allowed' => false,
            'premium' => true,
            'costs' => ['input' => 0.003, 'output' => 0.015],
        ],
        'claude-haiku-4' => [
            'id' => 'claude-haiku-4',
            'label' => 'Claude Haiku 4',
            'provider' => 'anthropic',
            'tier' => 'economy',
            'fallback_allowed' => true,
            'premium' => false,
            'costs' => ['input' => 0.00025, 'output' => 0.00125],
        ],
        // ── Google Gemini — proxy returns 501 "coming in V2" ─────────────
        'gemini-flash-1.5' => [
            'id' => 'gemini-flash-1.5',
            'label' => 'Gemini 1.5 Flash',
            'provider' => 'google',
            'tier' => 'economy',
            'fallback_allowed' => false,
            'premium' => false,
            'coming_soon' => true,
            'costs' => ['input' => 0.000075, 'output' => 0.0003],
        ],
    ],

    'internal_plans' => [
        'free' => [
            'id' => 'free',
            'name' => 'Free',
            'display_name' => 'Free',
            'price' => 0,
            'interval' => null,
            'trial_days' => 0,
            'billing_visible' => false,
            'self_serve_checkout' => false,
            'stripe_price_config' => null,
            'description' => 'Acces de base pour explorer Margexa.',
            'cta' => 'Creer mon compte',
            'features' => [
                'Dashboard de base',
                'Mode demo',
                '1 feature suivie',
            ],
            'entitlements' => [
                'dashboard' => true,
                'demo_mode' => true,
                'max_requests_day' => 100,
                'max_features' => 1,
                'observe_mode' => false,
                'enforcement' => false,
                'policies' => false,
                'proxy_access' => false,
                'cfo_reports' => false,
                'simulation' => false,
                'api_access' => false,
                'email_alerts' => false,
                'webhook_notifications' => false,
                'export_csv' => false,
                'export_pdf' => false,
                'multi_team' => false,
                'sso' => false,
                'sla' => false,
            ],
        ],
        'scan' => [
            'id' => 'scan',
            'name' => 'Diagnostic',
            'display_name' => 'Diagnostic',
            'price' => 490,
            'interval' => 'one_time',
            'trial_days' => 0,
            'billing_visible' => false,
            'self_serve_checkout' => false,
            'stripe_price_config' => 'price_scan',
            'description' => 'Audit approfondi unique avec rapport complet et plan d\'activation.',
            'cta' => 'Débloquer le Diagnostic',
            'features' => [
                'Rapport complet one-shot',
                'Recommandations de policies',
                'Plan d\'activation',
            ],
            'entitlements' => [
                'dashboard' => true,
                'demo_mode' => true,
                'max_requests_day' => 500,
                'max_features' => 3,
                'observe_mode' => false,
                'enforcement' => false,
                'policies' => false,
                'proxy_access' => false,
                'cfo_reports' => false,
                'simulation' => false,
                'api_access' => false,
                'email_alerts' => true,
                'webhook_notifications' => false,
                'export_csv' => false,
                'export_pdf' => true,
                'multi_team' => false,
                'sso' => false,
                'sla' => false,
                'full_audit_report' => true,
                'recommended_policies' => true,
                'activation_plan' => true,
            ],
        ],
        'observe' => [
            'id' => 'observe',
            'name' => 'Essentiel',
            'display_name' => 'Essentiel',
            'price' => 149,
            'interval' => 'month',
            'trial_days' => 14,
            'billing_visible' => false,
            'self_serve_checkout' => false,
            'stripe_price_config' => 'price_observe',
            'description' => 'Premier niveau de contrôle continu — policies de base et visibilité coût.',
            'cta' => 'Commencer avec Essentiel',
            'features' => [
                'Policies de base actives',
                'Visibilité clients / plans / requêtes',
                'Alertes email',
            ],
            'entitlements' => [
                'dashboard' => true,
                'demo_mode' => false,
                'max_requests_day' => 10000,
                'max_features' => 10,
                'observe_mode' => true,
                'enforcement' => true,
                'policies' => true,
                'proxy_access' => true,
                'cfo_reports' => false,
                'simulation' => false,
                'api_access' => false,
                'email_alerts' => true,
                'webhook_notifications' => false,
                'export_csv' => true,
                'export_pdf' => false,
                'multi_team' => false,
                'sso' => false,
                'sla' => false,
            ],
        ],
        'control' => [
            'id' => 'control',
            'name' => 'Control',
            'display_name' => 'Maîtrise',
            'price' => 349,
            'interval' => 'month',
            'trial_days' => 14,
            'billing_visible' => true,
            'self_serve_checkout' => true,
            'stripe_price_config' => 'price_control',
            'popular' => true,
            'description' => 'Controle runtime continu de votre marge support IA.',
            'cta' => 'Commencer le controle continu',
            'features' => [
                'Policies actives',
                'Economic routing',
                'Simulation et rapports CFO',
                'API et webhooks',
            ],
            'entitlements' => [
                'dashboard' => true,
                'demo_mode' => false,
                'max_requests_day' => 50000,
                'max_features' => 50,
                'observe_mode' => true,
                'enforcement' => true,
                'policies' => true,
                'proxy_access' => true,
                'cfo_reports' => true,
                'simulation' => true,
                'api_access' => true,
                'email_alerts' => true,
                'webhook_notifications' => true,
                'export_csv' => true,
                'export_pdf' => true,
                'multi_team' => false,
                'sso' => false,
                'sla' => false,
            ],
        ],
        'scale' => [
            'id' => 'scale',
            'name' => 'Sur mesure',
            'display_name' => 'Sur mesure',
            'price' => null,
            'interval' => 'month',
            'trial_days' => 0,
            'billing_visible' => true,
            'self_serve_checkout' => false,
            'stripe_price_config' => 'price_scale',
            'description' => 'Accompagnement avance pour les equipes avec exigences enterprise.',
            'cta' => 'Parler a l equipe',
            'features' => [
                'Multi-organisations',
                'SLA garanti',
                'Integrations custom',
                'Accompagnement dedie',
            ],
            'entitlements' => [
                'dashboard' => true,
                'demo_mode' => false,
                'max_requests_day' => null,
                'max_features' => null,
                'observe_mode' => true,
                'enforcement' => true,
                'policies' => true,
                'proxy_access' => true,
                'cfo_reports' => true,
                'simulation' => true,
                'api_access' => true,
                'email_alerts' => true,
                'webhook_notifications' => true,
                'export_csv' => true,
                'export_pdf' => true,
                'multi_team' => true,
                'sso' => true,
                'sla' => true,
                'dedicated_support' => true,
                'custom_integrations' => true,
            ],
        ],
    ],

    'public_offers' => [
        'audit_free' => [
            'id'          => 'audit_free',
            'name'        => 'Audit IA gratuit',
            'tagline'     => 'Identifiez les premières fuites de marge avant toute décision.',
            'price'       => 0,
            'price_note'  => 'gratuit',
            'kind'        => 'free',
            'free_href'   => '/audit',
            'cta'         => 'Lancer mon audit gratuit',
            'description' => 'Premier regard structuré sur vos flux IA pour comprendre où la marge s\'érode.',
            'features'    => [
                'Diagnostic initial',
                'Premiers signaux de dérive',
                'Priorités de risque',
                'Orientation vers la bonne formule',
            ],
        ],
        'scan' => [
            'id'             => 'scan',
            'name'           => 'Diagnostic',
            'tagline'        => 'Analyse approfondie en 7 jours pour identifier les fuites de marge réelles.',
            'price'          => 490,
            'price_was'      => 790,
            'urgency_badge'  => 'Offre lancement — jusqu\'au 31 mars',
            'price_note'     => 'paiement unique',
            'kind'           => 'product',
            'product'        => 'scan',
            'cta'            => 'Débloquer le Diagnostic',
            'register_offer' => 'scan',
            'description'    => 'Obtenez une lecture claire des coûts par feature, client ou plan, avec des recommandations activables.',
            'features'       => [
                'Top cost drivers par feature ou workflow',
                'Clients / segments à risque',
                '3 guardrails recommandés',
                'Estimation d\'impact mensuel',
                'Plan d\'activation concret',
            ],
            'guarantee'      => 'Si aucune fuite détectée, nous vous remboursons intégralement.',
            'delivery'       => 'Rapport livré sous 7 jours ouvrés, format PDF + accès dashboard.',
            'bonuses'        => [
                'Call de restitution 30 min inclus',
                'Template de politique activable immédiatement',
                'Estimation d\'économies sur 3 mois',
            ],
        ],
        'continuous_control' => [
            'id'             => 'continuous_control',
            'name'           => 'Maîtrise',
            'tagline'        => 'L\'offre recommandée pour passer du constat au contrôle actif.',
            'price'          => 349,
            'price_note'     => '/mois',
            'kind'           => 'subscription',
            'plan'           => 'control',
            'cta'            => 'Activer Maîtrise',
            'register_offer' => 'continuous_control',
            'description'    => 'Activez des guardrails métier et prouvez l\'impact économique de vos règles en continu.',
            'features'       => [
                'Policies actives',
                'Routage économique avancé',
                'Simulation et rapports CFO',
                'API et webhooks',
                'Preuve d\'impact',
            ],
            'badge' => 'Recommandé',
        ],
        'essential' => [
            'id'           => 'essential',
            'name'         => 'Essentiel',
            'tagline'      => 'Le point d\'entrée pour suivre et cadrer votre marge support IA.',
            'price'        => 149,
            'price_note'   => '/mois',
            'kind'         => 'contact',
            'badge_label'  => 'Abonnement',
            'cta'          => 'Commencer avec Essentiel',
            'contact_href' => '/contact?sujet=essentiel',
            'description'  => 'Mettez en place un premier niveau de contrôle continu sur vos flux IA sans complexité inutile.',
            'features'     => [
                'Suivi des fuites principales',
                'Policies de base',
                'Alertes simples',
                'Visibilité coût / usage',
                'Contrôle initial par feature ou plan',
            ],
        ],
        'scale' => [
            'id'           => 'scale',
            'name'         => 'Sur mesure',
            'tagline'      => 'Pour les équipes avec exigences avancées et contraintes spécifiques.',
            'price'        => null,
            'price_note'   => 'sur devis',
            'kind'         => 'contact',
            'cta'          => 'Parler à l\'équipe',
            'contact_href' => '/contact?sujet=scale',
            'description'  => 'Adaptez Margexa à une organisation plus large, plus intégrée et plus exigeante.',
            'features'     => [
                'Multi-organisations',
                'SLA garanti',
                'Intégrations custom',
                'Accompagnement dédié',
            ],
        ],
    ],
];
